name: Build Library

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Android or iOS'
        required: true
        type: choice
        options:
          - android
          - ios
      release_tag:
        description: 'Git tag for release (example: v1.2.3)'
        required: true
        type: string
      release_name:
        description: 'Release name (git tag if empty)'
        required: false
        type: string
      draft:
        description: 'Is draft?'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Is Rrerelease?'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build_android:
    if: ${{ github.event.inputs.platform == 'android' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.25.0'

      - name: Install sagernet gomobile and init
        run: |
          go install github.com/sagernet/gomobile/cmd/gomobile@latest
          gomobile init

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Setup OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          java --version

      - name: Build Android Library
        run: |
          go run ./cmd/internal/build_libbox -target android

      - name: Rename artifact with tag
        run: |
          mv libbox.aar "libbox-android-${{ github.event.inputs.release_tag }}.aar"

      - name: Upload Android Artifact (CI artifact)
        uses: actions/upload-artifact@v4
        with:
          name: libbox-aar
          path: libbox-android-${{ github.event.inputs.release_tag }}.aar

      - name: Publish GitHub Release (Android)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_name != '' && github.event.inputs.release_name || github.event.inputs.release_tag }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: libbox-android-${{ github.event.inputs.release_tag }}.aar
          token: ${{ secrets.GITHUB_TOKEN }}

  build_ios:
    if: ${{ github.event.inputs.platform == 'ios' }}
    runs-on: macos-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.25.0'

      - name: Install sagernet gomobile and init
        run: |
          go install github.com/sagernet/gomobile/cmd/gomobile@latest
          gomobile init

      - name: Build iOS Library
        run: |
          go run ./cmd/internal/build_libbox -target apple -platform ios

      - name: Zip XCFramework with tag
        run: |
          zip -r "Libbox-${{ github.event.inputs.release_tag }}.xcframework.zip" Libbox.xcframework

      - name: Upload iOS Artifact (CI artifact)
        uses: actions/upload-artifact@v4
        with:
          name: libbox-xcframework
          path: Libbox-${{ github.event.inputs.release_tag }}.xcframework.zip

      - name: Publish GitHub Release (iOS)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_tag }}
          name: ${{ github.event.inputs.release_name != '' && github.event.inputs.release_name || github.event.inputs.release_tag }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: Libbox-${{ github.event.inputs.release_tag }}.xcframework.zip
          token: ${{ secrets.GITHUB_TOKEN }}
