name: Build Library

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Android or iOS'
        required: true
        type: choice
        options:
          - android
          - ios

jobs:
  build_android:
    if: ${{ github.event.inputs.platform == 'android' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Install sagernet gomobile and init
        run: |
          go install github.com/sagernet/gomobile/cmd/gomobile@latest
          gomobile init

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Setup OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          java --version

      - name: Build Android Library
        run: |
          go run ./cmd/internal/build_libbox -target android

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libbox-aar
          path: libbox.aar

  build_ios:
    if: ${{ github.event.inputs.platform == 'ios' }}
    runs-on: macos-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Install sagernet gomobile and init
        run: |
          go install github.com/sagernet/gomobile/cmd/gomobile@latest
          gomobile init

      - name: Build iOS Library
        run: |
          go run ./cmd/internal/build_libbox -target apple -platform ios

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libbox-xcframework
          path: Libbox.xcframework